name: 📦 Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: Release
    permissions: write-all
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: 👾 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: 🚀 Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
